services:
  db:
    image: postgres:16
    container_name: encurtador_db
    restart: always
    environment:
      POSTGRES_USER: encurtador_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: encurtador
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U encurtador_user -d encurtador"]
      interval: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: encurtador_cache
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: encurtador_api
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - DATABASE_URL=postgresql://encurtador_user:password@db:5432/encurtador
      - REDIS_HOST=redis
    ports:
      - "8001:8000"
