services:
  db:
    image: postgres:16
    container_name: encurtador_db
    restart: always
    environment:
      POSTGRES_USER: encurtador_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: encurtador
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U encurtador_user -d encurtador"]
      interval: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: encurtador_cache
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    restart: always
    deploy:
      replicas: 3  # Criar múltiplos containers da API
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - DATABASE_URL=postgresql://encurtador_user:password@db:5432/encurtador
      - REDIS_HOST=redis
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    container_name: encurtador_lb
    restart: always
    depends_on:
      - app
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
