services:
  db:
    image: postgres:16
    container_name: encurtador_db
    restart: always
    environment:
      POSTGRES_USER: encurtador_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: encurtador
    ports:
      - "5433:5432"  # Mudamos a porta para 5433 para evitar conflitos com PostgreSQL local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U encurtador_user -d encurtador"]
      interval: 5s
      retries: 5

  app:
    build: .
    container_name: encurtador_api
    restart: always
    depends_on:
      db:
        condition: service_healthy  # Aguarda o banco estar pronto antes de iniciar a API
    environment:
      - DATABASE_URL=postgresql://encurtador_user:password@db:5432/encurtador
    ports:
      - "8001:8000"
