services:
  db:
    image: postgres:16
    container_name: encurtador_db
    restart: always
    environment:
      POSTGRES_USER: encurtador_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: encurtador
    ports:
      - "5433:5432"

  api:
    container_name: encurtador_api
    image: encurtador_url-app
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://encurtador_user:password@db:5432/encurtador"
    ports:
      - "8001:8000"

  redis:
    image: redis:alpine
    container_name: encurtador_cache
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: encurtador_queue
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"   # Porta para comunicação com aplicações
      - "15672:15672" # Painel web do RabbitMQ

  app:
    build: .
    restart: always
    depends_on:
      - db
      - redis
      - rabbitmq
    environment:
      - DATABASE_URL=postgresql://encurtador_user:password@db:5432/encurtador
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=user
      - RABBITMQ_PASS=password
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    container_name: encurtador_lb
    restart: always
    depends_on:
      - app
    ports:
      - "8002:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
